#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 29 11:41:23 2018

@author: drx
"""
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor 
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.externals import joblib
import os
import datetime

os.chdir('/media/shareddata/MIT/Capstone')
os.getcwd()

customer_clean = pd.read_csv('data/customer_clean')

#customer_clean = customer_clean.reset_index(drop=True)
#train test split
X = customer_clean[['schedule_miss', "1","2","3",'median', 'std']]

y = customer_clean['y']

X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.30, random_state=1992)

############################################
##   train RANDOM FOREST
############################################

regr = joblib.load('data/models/randomforest_11_11.joblib')
regr = RandomForestRegressor(n_estimators = 10,
                             criterion = 'mae',
                             random_state = 1992,
                             )
regr.fit(X_train, y_train)

###########################################
##  get model metrics
###########################################

feature_importance = pd.DataFrame(X_train.columns,
                                  regr.feature_importances_)
print(feature_importance)

y_hat = regr.predict(X_test)

print(regr.score(X_test, y_test))

test_data = pd.DataFrame(data = {'y_hat': y_hat,
                                 'y_test': y_test})

def print_metrics(y_hat, y_test):
    output = print('features: ', feature_importance, "\n",
                   'MAE: ', round(np.mean(abs(y_hat-y_test)), 2), "\n",
                   'MAPE: ', round(np.mean(abs(y_hat-y_test)/y_test), 4), "\n",
                   'RMSE: ', round(np.sqrt(np.mean((y_test - y_hat)**2)), 2), "\n"
                   ' R2: ', round(metrics.r2_score(y_test, y_hat),2)
                   )
    return output

print_metrics(test_data["y_hat"], test_data["y_test"])

#np.mean(abs(y_hat-y_test)/y_test)

###################################################
##      save model
###################################################

now = datetime.datetime.now()

filename = 'data/models/randomforest' + ''.join(['_', str(now.month), '_', str(now.day)]) +'.joblib'

from sklearn.externals import joblib
joblib.dump(regr, filename) 


