#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 19 12:07:36 2018

@author: Florian Krempl

Capstone Project: Predicting Transit time with Machine Learning
Partner Company: DAMCO/Maersk

"""

import os
import numpy as np
import pandas as pd

os.chdir('/media/shareddata/MIT/Capstone')
os.getcwd()

customer_clean = pd.DataFrame({'Carrier': [], 'ATA': [], 'ATD': [], 'ETD': [],
                              'Original Port Of Loading': [],
                              'Final Port Of Discharge': [],
                              'Original Port Of Loading Site': [],
                              'Final Port Of Discharge Site': []})

column_names = ['PO Line Uploaded', 'POH Client Date', 'POH Upload Date',
                'Book Date', 'Receipt Date', 'Consolidation Date',
                'ETD', 'ETA', 'ATD', 'ATA', 'Consignee',
                'PO Number', 'Origin Service', 'Destination Service', 'Consignee.1',
                'Carrier', 'VOCC Carrier', 'Carrier SCAC', 'CBL Number',
                'Booking Number', 'Shipper', 'Supplier', 'Buyer', 'Seller',
                'Original Port Of Loading', 'Original Port Of Loading Site',
                'Final Port Of Discharge', 'Final Port Of Discharge Site',
                'Actual Measurement', 'Earliest Receipt Date', 'Expected Receipt Date',
                'Latest Receipt Date', 'Actual Receipt Date',
                'Empty Equipment Dispatch-Actual', 'Gate In Origin-Actual',
                'Container Loaded On Vessel-Actual', 'Consolidation Date.1',
                'Container Unload From Vessel-Actual', 'Gate Out Destination-Actual',
                'Container Empty Return-Actual', 'Equipment Number',
                'Confirmation Date']

customers = ['USWA', 'USAD', 'USNI', 'USHO', 'USTA',
             'USDO', 'USCL', 'USHA', 'USHE']
# customer_name = 'USTE' does not work
customer = pd.read_csv('data/Capstone Project data/USHE.csv', encoding= 'latin1')
#customer[customer['Expected Receipt Date'].notna()]

for customer_name in customers:
    # load csv files
    print("start to load", customer_name, "...") 
    customer = pd.read_csv('data/Capstone Project data/' + customer_name +'.csv', encoding= 'latin1')
    print("loaded", customer_name, "starting to clean the dataframe")
    # test for unnecessary columns
    if customer.columns[0] == 'Unnamed: 0':
        customer = customer.drop(columns='Unnamed: 0')
        print('droped unnecessary index column')
    # get right column names    
    customer.columns = column_names
    # get real carrier
    customer["Carrier"] = np.where(customer['VOCC Carrier'].isna,
            customer["CBL Number"],    #"Carrier SCAC"
            customer["VOCC Carrier"])
    # get rid of missing data - select right columns
    customer = (customer.loc[customer['Final Port Of Discharge Site'] == 'UNITED STATES']
                        .loc[customer['ETD'].notna()]
                        .loc[customer['Expected Receipt Date'].notna()]
                        .loc[customer['Container Unload From Vessel-Actual'].notna()]
                        .loc[:,['Shipper', 'Carrier',
                                'Original Port Of Loading',
                                'Original Port Of Loading Site',
                                'Final Port Of Discharge',
                                'Final Port Of Discharge Site',
                                'Origin Service', 
                                'Book Date', 'Expected Receipt Date', 
                                'Gate In Origin-Actual', 'Consolidation Date',
                                'ETD', 'ATD','ETA', 'ATA',
                                'Container Unload From Vessel-Actual',
                                'Equipment Number']])
    
    customer['customer'] = customer_name
    # append to customer_clean
    print("appending", customer_name, "to customer_clean", "\n") 
    customer_clean = customer_clean.append(customer)

# get date to right format
date_columns = ['Gate In Origin-Actual','Container Unload From Vessel-Actual']
customer_clean[date_columns] = customer_clean[date_columns].replace('-', '/', regex = True)

for column in date_columns:
    customer_clean[column] = pd.to_datetime(customer_clean[column], format =  '%d/%m/%Y')
    print(['finished converting column', column, 'to date'])

# get y column
customer_clean['y'] = customer_clean['Container Unload From Vessel-Actual']-customer_clean['Gate In Origin-Actual']
customer_clean['y'] = customer_clean['y'].dt.days
    

    
