#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov  2 12:52:18 2018

@author: drx
"""

import os
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split




os.chdir('/media/shareddata/MIT/Capstone')
os.getcwd()

customer = pd.read_csv('data/data2.csv')
customer.columns


groups = customer.groupby(['Carrier',
                           'Original Port Of Loading',
                           'Final Port Of Discharge'])

summary = groups['Booking Number'].agg(np.size)
summary

summary.plot.hist(grid=True, bins=10, rwidth=0.9, color='#607c8e')

summary.to_csv('data/summary_carrier_routes', sep=',')


customer['n_obs'] = customer.goupby(['Carrier',
                           'Original Port Of Loading',
                           'Final Port Of Discharge'])
customer.groupby(['Carrier'])['ATA'].transform(np.mean)

customer['n_obs'] = 
df['A-month-sum'] = df.groupby('month')['A'].transform(sum) 




